### ISSUE TITLE
[New Feature] Interactive Login

### ISSUE THREAD

**Issue by avcaliani** [isabelle-vc/googly#5]
The idea is to click at the login button, then retrieve the user GitHub picture and name via a mocked API.

### API Spec

> Suggestion: Use FastAPI

**Endpoint**: `GET /`  
**Response** 👇

```json
{
  "random_emoji": "🪴",
  "current_datetime": "2024-01-01T00:00:00"
}
```

**Endpoint**: `POST /login`  

**Body** 👇

```json
{
  "nickname": "avcaliani",
  "password": "*********"
}
```

**Response** 👇

```json
{
  "user_nickname": "avcaliani",
  "user_picture": "https://avatars.githubusercontent.com/u/15377830?v=4",
  "current_datetime": "2024-01-01T00:00:00"
}
```

---

## Tasks

- [x] Update the front to support the Login feature
- [x] Create the API (Python 3.9.6)
- [ ] Trigger the API using JS
- [ ] Update the HTML with API Response
